config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/signup', to: 'auth#signup'
  get '/login', to: 'auth#login'
  post '/login', to: 'auth#signin'
  delete '/logout', to: 'auth#logout'

  resources :users, only: [:create, :edit, :update, :show, :index]
  resources :articles

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_secure_password

  validates :username,
            presence: true,
            length: { minimum: 3, maximum: 25 },
            uniqueness: { case_sensitive: false }
  validates :email,
            presence: true,
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\z/ }

  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :is_auth

  def current_user
    user_id = session[:user_id]
    return nil if user_id.nil?

    @current_user ||= User.find(user_id)
  end

  def is_auth
    !!current_user
  end

  def require_user
    unless is_auth
      flash[:alert] = 'You must by logged in to perform this action'
      redirect_to login_path
    end
  end

  def require_is_not_auth
    if is_auth
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_owner, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(get_article_data)
    @article.user = current_user

    if @article.save
      handle_save_success("Article was created successfully!")
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(get_article_data)
      handle_save_success("Article was updated successfully!")
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def get_article_data
    params.require(:article).permit(:title, :description)
  end

  def handle_save_success(message)
    flash[:notice] = message
    redirect_to @article
  end

  def require_owner
    if current_user != @article.user
      flash[:alert] = "You can only edit or delete your own articles"
      redirect_to article_path(@article)
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :require_is_not_auth, only: [:signup, :login, :signin]

  def signup
    @user = User.new
  end

  def login
  end

  def signin
    email = params[:auth][:email].downcase
    password = params[:auth][:password]
    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:alert] = 'Invalid email or password'

      render 'login'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if is_auth
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_is_not_auth, only: [:create]
  before_action :require_user, only: [:edit, :update]
  before_action :require_owner, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(get_user_data)

    if @user.save
      flash[:notice] = "Hi, #{@user.username}. Welcome to Ruby Blog!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'signup'
    end
  end

  def edit
  end

  def update
    if @user.update(get_user_data)
      flash[:notice] = "Your profile successfully updated!"

      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def get_user_data
    params.require(:user).permit(:username, :email, :password)
  end

  def require_owner
    if @user != current_user
      flash[:alert] = 'You can edit or delete only own profile'
      redirect_to user_path(@user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_for(user, options = { size: 200, class: '' })
    image_tag("https://i.pravatar.cc/#{options[:size]}?u=#{user.email}", alt: user.username, class: options[:class] || "rounded shadow")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles-list.html.erb
<div class="w-100">
  <% articles.each do |article| %>
    <div class="card text-center mt-3">
      <div class="card-body">
        <h5 class="card-title"><%= article.title %></h5>
        <p class="card-text"><%= article.description %></p>
        <%= link_to 'Show', article_path(article), class: 'btn btn-outline-primary' %>
        <% if is_auth && article.user == current_user %>
          <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-success' %>
          <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
        <% end %>
      </div>
      <div class="card-footer text-body-secondary d-flex justify-content-between">
        <div>
          By <%= article.user.username %>
        </div>
        <div>
          Created <%= time_ago_in_words article.created_at %> ago, updated <%= time_ago_in_words article.updated_at %>
          ago
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class='articles__form'>
  <%= render "shared/errors", model: @article %>

  <%= form_with model: @article, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :description, class: 'form-label' %>
      <%= f.text_area :description, class: 'form-control', rows: 8 %>
    </div>
    <div class="mb-3">
      <%= f.submit class: 'btn btn-outline-primary' %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container my-3 d-flex flex-column align-items-center">
  <h1>Update Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container mb-3">
  <%= render "articles/articles-list", articles: @articles %>
  <%= render "shared/pagination", list: @articles %>
</div>

app/views/articles/new.html.erb
<div class="container my-3 d-flex flex-column align-items-center">
  <h1>Create Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container my-3">
  <h1 class="text-center"><%= @article.title %></h1>
  <div class="card text-center mt-3">
    <% if is_auth && @article.user == current_user %>
      <div class="card-header d-flex justify-content-end">
        <div>
          <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-success' %>
          <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
        </div>
      </div>
    <% end %>
    <div class="card-body">
      <p class="card-text"><%= @article.description %></p>
    </div>
    <div class="card-footer text-body-secondary d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center gap-3">
        By <%= @article.user.username %>
        <%= link_to avatar_for(@article.user, { size: 60 }), user_path(@article.user), class: "rounded-circle overflow-hidden" %>
      </div>
      <div>
        Created <%= time_ago_in_words @article.created_at %> ago, updated <%= time_ago_in_words @article.updated_at %>
        ago
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h5>About Us</h5>
        <p class="small">
          A brief description of the website or company. Work hard, dream big, and make it happen!
        </p>
      </div>
      <div class="col-md-6 d-flex flex-column align-items-end">
        <ul class="list-unstyled text-white">
          <li>Email: <a href="mailto:info@example.com" class="text-white">info@example.com</a></li>
          <li>Phone: <a href="tel:+1234567890" class="text-white">+123 456 7890</a></li>
          <li>Address: 123 Main St, City</li>
        </ul>
      </div>
    </div>
    <div class="text-center mt-3 border-top pt-3">
      <p class="small mb-0">© <%= Time.current.year %> Ruby Blog. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container">
      <%= link_to "Ruby Blog", root_path, class: "navbar-brand text-white" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% unless is_auth %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link text-white #{'active' if current_page?(root_path)}" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class: "nav-link text-white #{'active' if current_page?(articles_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link text-white #{'active' if current_page?(users_path)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link text-white #{'active' if current_page?(about_path)}" %>
          </li>
        </ul>
        <div class="d-flex">
          <div class="mx-3 d-flex gap-3">
            <% if is_auth %>
              <%= link_to "Create new", new_article_path, class: 'btn btn-primary' %>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hi, <%= current_user.username %>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Profile", user_path(current_user), class: 'dropdown-item' %>
                  <li>
                    <%= link_to "Logout", logout_path, method: :delete, class: 'dropdown-item text-danger' %>
                  <li>
                </ul>
              </div>
            <% else %>
              <%= link_to "Login", login_path, class: 'btn btn-primary' %>
              <%= link_to "Sign Up", signup_path, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-dismissible fade show my-3 <%= name == 'alert' ? 'alert-danger' : 'alert-success' %>" role="alert">
        <div>
          <%= msg %>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/header' %>
<main class="bg-body-secondary">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container my-3">
  <h1 class="text-center">About Us</h1>
  <p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
    standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a
    type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
    remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
    Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of
    Lorem Ipsum.
  </p>
  <p>
    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its
    layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to
    using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web
    page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web
    sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on
    purpose (injected humour and the like).
  </p>
  <p>
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin
    literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney
    College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and
    going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes
    from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,
    written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first
    line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
  </p>
  <p>
    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32
    and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,
    accompanied by English versions from the 1914 translation by H. Rackham.
  </p>
</div>

app/views/pages/home.html.erb
<div class="d-flex justify-content-center align-items-center flex-column home__banner flex-grow-1">
  <h1 class='text-white'>Ruby Blog</h1>
  <p class='text-white'>This is a test application for exploring features and development practices in Ruby on
    Rails.</p>

  <%= link_to "Sign Up", signup_path, class: "btn btn-primary" %>
</div>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4>Validation failed</h4>
      <ul>
<% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
<% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_pagination.html.erb
<div class="d-flex justify-content-center mt-3">
  <div class="apple_pagination">
    <%= will_paginate list, :container => false %>
  </div>
</div>

app/views/users/_form.html.erb
<div>
  <%= render "shared/errors", model: @user %>

  <%= form_with model: @user, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :username, class: 'form-label' %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :email, class: 'form-label' %>
      <%= f.text_field :email, class: 'form-control', type: 'email' %>
    </div>
    <div class="mb-3">
      <%= f.label :password, class: 'form-label' %>
      <%= f.text_field :password, class: 'form-control', type: 'password' %>
    </div>
    <div class="mb-3">
      <%= f.submit @user.new_record? ? "Sign Up" : "Update", class: 'btn btn-outline-primary' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container my-3 d-flex flex-column align-items-center flex-grow-1">
  <div class="align-self-end mb-2">
    <%= link_to 'Profile', user_path(@user), class: 'btn btn-outline-primary' %>
  </div>
  <div class="users-form">
    <h1>Edit profile</h1>
    <%= render "users/form" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container my-3">
  <h1 class="mb-3 text-center">Users</h1>
  <div>
    <% @users.each do |user| %>
      <div class="card text-center mt-3">
        <div class="card-header d-flex justify-content-end">
          <div>
            <%= link_to 'Profile', user_path(user), class: 'btn btn-outline-primary' %>
            <% if is_auth && user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: 'btn btn-outline-success' %>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <p class="card-text"><%= user.email %></p>
          <%= avatar_for user %>
        </div>
        <div class="card-footer text-body-secondary d-flex justify-content-between">
          <div>
            <%= pluralize(user.articles.count, "Articles") %>
          </div>
          <div>
            Created <%= time_ago_in_words user.created_at %> ago, updated <%= time_ago_in_words user.updated_at %>
            ago
          </div>
        </div>
      </div>
    <% end %>
    <%= render "shared/pagination", list: @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container d-flex justify-content-center align-items-center flex-grow-1">
  <div class="signup">
    <h1>Sign Up</h1>
    <%= render "users/form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container my-3 d-flex flex-column align-items-center">
  <% if is_auth && @user == current_user %>
    <div class="align-self-end mb-2">
      <%= link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-outline-success' %>
    </div>
  <% end %>
  <div class="mb-3 text-center">
    <h1><%= @user.username %>'s profile</h1>
    <p class="text-secondary-emphasis"><%= @user.email %></p>
  </div>
  <div class="d-flex justify-content-between mb-4">
    <%= avatar_for @user %>
  </div>

  <h3>Articles</h3>
  <%= render "articles/articles-list", articles: @articles %>
  <%= render "shared/pagination", list: @articles %>
</div>